### ISSUE TITLE
Possible problems when using port 443

### ISSUE THREAD

**Issue by ARlayers** [radixdlt/node-runner#9]
It can cause problems if the Node software is installed on a server running a webserver in parallel.
Maybe it would be better to choose a different standard port.

**Comment by blenessy** [comment]
Ack, will look into this. 

I will also investigate whether we can support different API (443) ports per node on the same network.
Current design enforces all nodes to use the **same API port ** on a network.

**Comment by ytseschew** [comment]
An advantage of using port 443 is that few governments/corporations will be blocking it. However, they may enforce standard SSL on it. 

The disadvantage is that it's much less flexible. If you want to run both a web-server and Radix then you're out of luck. Also, it means that if an attacker does want to block it then they know exactly which port to block.

It seems to me that since we have to be able to find other nodes via IP in some way that it should be possible to include the port in the results of that search. The default port could be 443, but some servers could opt to use other ports as needed.
